### ISSUE TITLE
Error installing v1.1.6 on Moodle 4.3.3+ (Build: 20240405)

### ISSUE THREAD

**Issue by ElectricCircus** [harshil8595/moodle-block_timezoneclock#10]
When installing this plugin, after the server requirements checks the installation shows this message:
"Detectado un error de codificación, debe ser corregido por un programador: Incorrect syntax in plugin supported declaration in timezoneclock".
URL: https://mysitehere/admin/index.php?cache=0&upgradekeyhash=818e366ecbb224bd7b2d3310200b140d7f538dc8&confirmrelease=1&confirmplugincheck=0&confirmupgrade=1

Clicking on the only button available, Continue, causes to restart the process. The site cannot be recovered from this status.

**Comment by harshil8595** [comment]
Thanks for reporting issue.

I will fix as soon as possible.

**Comment by harshil8595** [comment]
Hi @ElectricCircus 

I have fixed issue and released new version.
