### ISSUE TITLE
Configuration changes do not stick

### ISSUE THREAD

**Issue by ptabak** [harshil8595/moodle-block_timezoneclock#8]
Hi, Thank you for providing what looks like a really useful block. Unfortunately when I try to configure the block to show multiple timezones, on save the block only displays a single timezone (Europe/London).

On reopening config, there is only one timezone configured which always defaults to the first option in the select list (Africa/Abidjan). Have tested on both Firefox and Chrome, uninstalled and reinstalled block and purged caches... but the problem persists.

MAMP 6.6
PHP 7.4.21
Moodle 4.1
block_timezoneclock 1.1.4

**Comment by harshil8595** [comment]
Hi @ptabak I've addressed issue.

Releasing fix asap.

**Comment by ptabak** [comment]
Thank you Harshil, I've made the change locally and now all works as expected!

**Comment by harshil8595** [comment]
> Thank you Harshil, I've made the change locally and now all works as expected!

Thanks for reporting issue. I've fixed issue on main branch as well
