### ISSUE TITLE
Display error on Mac OSX Ventura

### ISSUE THREAD

**Issue by robouden** [harshil8595/moodle-block_timezoneclock#9]
On Mac OSX Ventura running the plugin, the following error:
![Screenshot 2023-05-31 at 11 04 58](https://github.com/harshil8595/moodle-block_timezoneclock/assets/1387190/dc07146b-51f1-4a40-90b1-614921f68769)

**Comment by harshil8595** [comment]
Thanks for reporting @robouden 

Needs following details required to replicate issue:

- Moodle version
- Moodle theme
- Browser version number
- Plugin version

**Comment by harshil8595** [comment]
Hi @robouden,

I'm closing this issue because Required details missing.
